# Generated by Django 5.0.14 on 2026-06-15 08:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='task_files/%Y/%m/', verbose_name='文件')),
                ('original_name', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('file_type', models.CharField(choices=[('DOCUMENT', '文档'), ('IMAGE', '图片'), ('EXCEL', '表格'), ('WPS', 'WPS文件'), ('PDF', 'PDF文件'), ('OTHER', '其他')], default='OTHER', max_length=20, verbose_name='文件类型')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='文件大小(bytes)')),
                ('mime_type', models.CharField(blank=True, default='', max_length=100, verbose_name='MIME类型')),
                ('sha256', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='SHA256')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='下载次数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='tasks.task', verbose_name='关联任务')),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '任务附件',
                'verbose_name_plural': '任务附件',
                'db_table': 'task_files',
                'ordering': ['-created_at'],
            },
        ),
    ]
