# Generated by Django 5.0.14 on 2026-06-15 08:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('format', models.CharField(choices=[('EXCEL', 'Excel'), ('PDF', 'PDF'), ('CSV', 'CSV')], max_length=10, verbose_name='格式')),
                ('status', models.CharField(choices=[('PENDING', '等待中'), ('GENERATING', '生成中'), ('COMPLETED', '已完成'), ('FAILED', '失败')], default='PENDING', max_length=20, verbose_name='状态')),
                ('filters', models.JSONField(blank=True, default=dict, verbose_name='筛选条件')),
                ('file', models.FileField(blank=True, upload_to='exports/%Y/%m/', verbose_name='导出文件')),
                ('file_name', models.CharField(blank=True, default='', max_length=255, verbose_name='文件名')),
                ('row_count', models.PositiveIntegerField(default=0, verbose_name='行数')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_jobs', to=settings.AUTH_USER_MODEL, verbose_name='请求人')),
            ],
            options={
                'verbose_name': '导出任务',
                'verbose_name_plural': '导出任务',
                'db_table': 'export_jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
