# Generated by Django 5.0.14 on 2026-06-16 02:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0002_task_reward_points'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('TASK_COMPLETED', '完成任务'), ('TASK_ASSIGNED', '被分配任务'), ('TASK_CLAIMED', '领取任务')], max_length=20, unique=True, verbose_name='动作类型')),
                ('mode', models.CharField(choices=[('FIXED', '固定积分'), ('PRIORITY_BASED', '按优先级'), ('CUSTOM', '自定义')], default='FIXED', max_length=20, verbose_name='分配模式')),
                ('base_points', models.IntegerField(default=10, verbose_name='基础积分')),
                ('priority_multiplier', models.FloatField(default=1.0, help_text='PRIORITY_BASED 模式下：URGENT=4x, HIGH=3x, MEDIUM=2x, LOW=1x', verbose_name='优先级倍率')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '积分规则',
                'verbose_name_plural': '积分规则',
                'db_table': 'point_rules',
            },
        ),
        migrations.CreateModel(
            name='PointBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_earned', models.IntegerField(default=0, verbose_name='累计获得')),
                ('total_spent', models.IntegerField(default=0, verbose_name='累计消费')),
                ('balance', models.IntegerField(default=0, verbose_name='当前余额')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='point_balance', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '积分余额',
                'verbose_name_plural': '积分余额',
                'db_table': 'point_balances',
            },
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('EARN', '获得'), ('DEDUCT', '扣除')], max_length=10, verbose_name='类型')),
                ('points', models.IntegerField(verbose_name='积分变动')),
                ('balance_after', models.IntegerField(verbose_name='变动后余额')),
                ('reason', models.CharField(blank=True, default='', max_length=200, verbose_name='原因')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_transactions', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '积分流水',
                'verbose_name_plural': '积分流水',
                'db_table': 'point_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
