# Generated by Django 5.0.14 on 2026-06-15 08:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('LOGIN', '登录'), ('LOGOUT', '登出'), ('CREATE', '创建'), ('UPDATE', '修改'), ('DELETE', '删除'), ('EXPORT', '导出'), ('IMPORT', '导入'), ('ADMIN', '管理操作')], db_index=True, max_length=20, verbose_name='操作类型')),
                ('resource_type', models.CharField(db_index=True, max_length=50, verbose_name='资源类型')),
                ('resource_id', models.CharField(blank=True, default='', max_length=50, verbose_name='资源ID')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('detail', models.JSONField(blank=True, default=dict, verbose_name='详情')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.CharField(blank=True, default='', max_length=300, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='audit_logs_user_id_6193b2_idx'), models.Index(fields=['action', 'resource_type'], name='audit_logs_action_fe069e_idx')],
            },
        ),
    ]
