# Generated by Django 5.0.14 on 2026-06-15 08:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_no', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='任务编号')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('description', models.TextField(blank=True, default='', verbose_name='详细描述')),
                ('status', models.CharField(choices=[('PENDING', '待领取'), ('IN_PROGRESS', '进行中'), ('IN_REVIEW', '待审核'), ('COMPLETED', '已完成'), ('REJECTED', '已退回'), ('CANCELLED', '已取消')], db_index=True, default='PENDING', max_length=20, verbose_name='状态')),
                ('priority', models.CharField(choices=[('LOW', '低'), ('MEDIUM', '中'), ('HIGH', '高'), ('URGENT', '紧急')], default='MEDIUM', max_length=10, verbose_name='优先级')),
                ('progress', models.PositiveSmallIntegerField(default=0, verbose_name='进度(%)')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='截止日期')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('custom_fields', models.JSONField(blank=True, default=dict, verbose_name='自定义字段')),
                ('external_id', models.CharField(blank=True, default='', max_length=100, verbose_name='外部ID(导入用)')),
                ('source', models.CharField(blank=True, default='MANUAL', max_length=20, verbose_name='来源')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_tasks', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
                'db_table': 'tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='评论内容')),
                ('is_internal', models.BooleanField(default=False, verbose_name='内部评论(仅组长/管理员可见)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_comments', to=settings.AUTH_USER_MODEL, verbose_name='评论人')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tasks.task')),
            ],
            options={
                'verbose_name': '任务评论',
                'verbose_name_plural': '任务评论',
                'db_table': 'task_comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATED', '创建'), ('STATUS_CHANGE', '状态变更'), ('ASSIGNED', '分配'), ('UPDATED', '更新'), ('COMMENTED', '评论'), ('IMPORTED', '导入'), ('EXPORTED', '导出')], max_length=20, verbose_name='操作类型')),
                ('old_value', models.JSONField(blank=True, default=dict, verbose_name='变更前')),
                ('new_value', models.JSONField(blank=True, default=dict, verbose_name='变更后')),
                ('diff', models.JSONField(blank=True, default=dict, verbose_name='差异')),
                ('note', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_actions', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tasks.task')),
            ],
            options={
                'verbose_name': '任务历史',
                'verbose_name_plural': '任务历史',
                'db_table': 'task_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', 'priority'], name='tasks_status_0fbdac_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assignee', 'status'], name='tasks_assigne_972e70_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['deadline'], name='tasks_deadlin_7f16a6_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['-created_at'], name='tasks_created_d28591_idx'),
        ),
    ]
