# Generated by Django 5.0.14 on 2026-06-16 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reward_points',
            field=models.IntegerField(default=0, verbose_name='任务积分'),
        ),
    ]
