# Generated by Django 5.0.14 on 2026-06-17 09:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def migrate_assignee_to_participants(apps, schema_editor):
    """将存量单人 assignee 任务迁移为 TaskParticipant（PARTICIPANT 角色）。"""
    Task = apps.get_model('tasks', 'Task')
    TaskParticipant = apps.get_model('tasks', 'TaskParticipant')
    tasks_with_assignee = Task.objects.filter(assignee__isnull=False)
    for task in tasks_with_assignee:
        TaskParticipant.objects.get_or_create(
            task=task,
            user=task.assignee,
            defaults={
                'role': 'PARTICIPANT',
                'points': task.reward_points,
                'status': 'ACCEPTED' if task.status != 'PENDING' else 'INVITED',
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_reward_points'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='current_claimers',
            field=models.PositiveIntegerField(default=0, verbose_name='已领取人数'),
        ),
        migrations.AddField(
            model_name='task',
            name='max_claimers',
            field=models.PositiveIntegerField(blank=True, help_text='固定揭榜模式下的名额数，null 表示不限', null=True, verbose_name='揭榜名额'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_mode',
            field=models.CharField(choices=[('ASSIGNED', '派发'), ('FREE_CLAIM', '自由揭榜'), ('FIXED_CLAIM', '固定揭榜')], db_index=True, default='ASSIGNED', max_length=20, verbose_name='任务模式'),
        ),
        migrations.CreateModel(
            name='TaskParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('CHIEF_LEAD', '总牵头人'), ('GROUP_LEAD', '小组牵头'), ('PARTICIPANT', '参与'), ('CLAIMER', '领取人')], max_length=20, verbose_name='角色')),
                ('points', models.IntegerField(verbose_name='该角色积分')),
                ('status', models.CharField(choices=[('INVITED', '已邀请'), ('ACCEPTED', '已接受'), ('COMPLETED', '已完成'), ('CANCELLED', '已取消')], default='INVITED', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_participations', to=settings.AUTH_USER_MODEL, verbose_name='参与者')),
            ],
            options={
                'verbose_name': '任务参与者',
                'verbose_name_plural': '任务参与者',
                'db_table': 'task_participants',
                'indexes': [models.Index(fields=['task', 'role'], name='task_partic_task_id_4cd076_idx')],
                'unique_together': {('task', 'user')},
            },
        ),
        migrations.RunPython(migrate_assignee_to_participants, migrations.RunPython.noop),
    ]
