# Generated by Django 5.0.14 on 2026-06-22 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_add_task_mode_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completion_criteria',
            field=models.TextField(blank=True, default='', verbose_name='完成标准'),
        ),
        migrations.AddField(
            model_name='task',
            name='dispatcher_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='派发人'),
        ),
        migrations.AddField(
            model_name='task',
            name='output',
            field=models.TextField(blank=True, default='', verbose_name='产出要求'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_source',
            field=models.CharField(blank=True, default='', help_text='如：关于征集公司2026年第一批...、部门自选等', max_length=200, verbose_name='任务来源'),
        ),
    ]
