# Generated by Django 5.0.14 on 2026-06-15 08:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='imports/%Y/%m/', verbose_name='导入文件')),
                ('original_name', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('file_format', models.CharField(max_length=10, verbose_name='文件格式')),
                ('status', models.CharField(choices=[('PENDING', '待解析'), ('PARSING', '解析中'), ('PREVIEW', '待确认'), ('CONFIRMING', '导入中'), ('COMPLETED', '已完成'), ('FAILED', '失败')], default='PENDING', max_length=20, verbose_name='状态')),
                ('total_rows', models.PositiveIntegerField(default=0, verbose_name='总行数')),
                ('valid_rows', models.PositiveIntegerField(default=0, verbose_name='有效行数')),
                ('skipped_rows', models.PositiveIntegerField(default=0, verbose_name='跳过行数')),
                ('error_rows', models.PositiveIntegerField(default=0, verbose_name='错误行数')),
                ('preview_data', models.JSONField(blank=True, default=list, verbose_name='预览数据')),
                ('column_mapping', models.JSONField(blank=True, default=dict, verbose_name='列映射')),
                ('errors', models.JSONField(blank=True, default=list, verbose_name='错误详情')),
                ('imported_task_ids', models.JSONField(blank=True, default=list, verbose_name='已导入任务ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_sessions', to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '导入会话',
                'verbose_name_plural': '导入会话',
                'db_table': 'import_sessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
